version: "3.8"

services:
  web-service:
    build:
      context: ./web-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  subscriber-service:
    build:
      context: ./subscriber-service
      dockerfile: Dockerfile
    depends_on:
      - redis
